server:
  port: 8080

api:
  url:
    domain: "jsonplaceholder.typicode.com"
    endpoint:
      user: "/users"
      post: "/posts"

# Postgres
spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/bc2405p_db"
    username: "postgres"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # update
      # ddl-auto: none -> ?

# MySQL
# spring:
#   datasource:
#     driverClassName: "com.mysql.cj.jdbc.Driver"
#     url: "jdbc:mysql://localhost:3306/bc2405p_db"
#     username: "root"
#     password: "admin1234"
#   jpa:
#     show-sql: true
#     properties:
#       hibernate:
#         ddl-auto: create # update
#         dialect: "org.hibernate.dialect.MySQL8Dialect"