server:
  port: 8080

api:
  url:
    domain: "jsonplaceholder.typicode.com"
    endpoint:
      user: "users"

spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/bc2405p_db"
    username: "root"
    password: "admin1234"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
  application:
    name: USER-SERVICE